// constants of random indonesian food

export const MAKANAN_INDONESIA = [
    "Nasi Goreng",
    "Mie Goreng",
    "Sate",
    "Rendang",
    "Soto",
    "Gado-Gado",
    "Nasi Uduk",
    "Nasi Kuning",
    "Nasi Padang",
    "Ayam Goreng",
    "Ayam Bakar",
    "Ayam Taliwang",
    "Ayam Betutu",
    "Ayam Penyet",
    "Ayam Pop",
    "Ikan Bakar",
    "Ikan Goreng",
    "Ikan Pepes",
    "Ayam Geprek",
    "Mie Ayam",
    "Mie Bakso",
    "Mie Aceh",
    "Mie Kocok",
    "Mie Gacoan",
    "Pempek",
    "Pecel Lele",
    "Pisang Goreng",
    "Ketoprak",
    "Lontong Sayur",
    "Martabak",
    "Bakso",
    "Sop Buntut",
    "Sop Iga",
]